#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

runApplication setFields

isParallel=0
if isParallel
then
    runApplication decomposePar

    runParallel $(getApplication)

    runApplication reconstructPar
else
    runApplication $(getApplication)
fi

#------------------------------------------------------------------------------
